/**
 * Prisma generate does not emit index.*; Vercel/runtime expect a stable entry.
 * Run after `prisma generate` (see postinstall).
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(fileURLToPath(new URL("..", import.meta.url)));
const indexPath = resolve(root, "lib/db/generated/prisma/index.ts");
writeFileSync(
  indexPath,
  `/* generated by scripts/prisma-index.mjs after prisma generate */
export * from "./client.js";
`,
  "utf8",
);
